apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket
  labels:
    app: ticket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticket
  template:
    metadata:
      labels:
        app: ticket
    spec:
      automountServiceAccountToken: false
      containers:
        - name: ticket
          envFrom:
            - configMapRef:
                name: ticket-service-config
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          image: ghcr.io/soldevlife-assesment-2024-s1/ticket-service:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: ticket-service
spec:
  selector:
    app: ticket
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
